python run_subprocess.py CrossValidation 0.0 KNN
python run_subprocess.py CrossValidation 0.0 OLS
python run_subprocess.py CrossValidation 0.0 Lasso
python run_subprocess.py CrossValidation 0.0 Ridge
python run_subprocess.py CrossValidation 0.0 ElasticNet
python run_subprocess.py CrossValidation 0.0 DT
#python run_subprocess.py CrossValidation 0.0 LGBM
python run_subprocess.py CrossValidation 0.0 RF
python run_subprocess.py CrossValidation 0.0 MLP
python run_subprocess.py CrossValidation 0.0 SVM
echo 1
python run_subprocess.py TraditionalSCV 0.0 KNN
python run_subprocess.py TraditionalSCV 0.0 OLS
python run_subprocess.py TraditionalSCV 0.0 Lasso
python run_subprocess.py TraditionalSCV 0.0 Ridge
python run_subprocess.py TraditionalSCV 0.0 ElasticNet
python run_subprocess.py TraditionalSCV 0.0 DT
#python run_subprocess.py TraditionalSCV 0.0 LGBM
python run_subprocess.py TraditionalSCV 0.0 RF
python run_subprocess.py TraditionalSCV 0.0 MLP
python run_subprocess.py TraditionalSCV 0.0 SVM
echo Optimistic
python run_subprocess.py Optimistic 0.0 KNN
python run_subprocess.py Optimistic 0.0 OLS
python run_subprocess.py Optimistic 0.0 Lasso
python run_subprocess.py Optimistic 0.0 Ridge
python run_subprocess.py Optimistic 0.0 ElasticNet
python run_subprocess.py Optimistic 0.0 DT
#python run_subprocess.py Optimistic 0.0 LGBM
python run_subprocess.py Optimistic 0.0 RF
python run_subprocess.py Optimistic 0.0 MLP
python run_subprocess.py Optimistic 0.0 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.0 KNN
python run_subprocess.py RegGBSCV 0.0 OLS
python run_subprocess.py RegGBSCV 0.0 Lasso
python run_subprocess.py RegGBSCV 0.0 Ridge
python run_subprocess.py RegGBSCV 0.0 ElasticNet
python run_subprocess.py RegGBSCV 0.0 DT
#python run_subprocess.py RegGBSCV 0.0 LGBM
python run_subprocess.py RegGBSCV 0.0 RF
python run_subprocess.py RegGBSCV 0.0 MLP
python run_subprocess.py RegGBSCV 0.0 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.1 KNN
python run_subprocess.py RegGBSCV 0.1 OLS
python run_subprocess.py RegGBSCV 0.1 Lasso
python run_subprocess.py RegGBSCV 0.1 Ridge
python run_subprocess.py RegGBSCV 0.1 ElasticNet
python run_subprocess.py RegGBSCV 0.1 DT
#python run_subprocess.py RegGBSCV 0.1 LGBM
python run_subprocess.py RegGBSCV 0.1 RF
python run_subprocess.py RegGBSCV 0.1 MLP
python run_subprocess.py RegGBSCV 0.1 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.2 KNN
python run_subprocess.py RegGBSCV 0.2 OLS
python run_subprocess.py RegGBSCV 0.2 Lasso
python run_subprocess.py RegGBSCV 0.2 Ridge
python run_subprocess.py RegGBSCV 0.2 ElasticNet
python run_subprocess.py RegGBSCV 0.2 DT
#python run_subprocess.py RegGBSCV 0.2 LGBM
python run_subprocess.py RegGBSCV 0.2 RF
python run_subprocess.py RegGBSCV 0.2 MLP
python run_subprocess.py RegGBSCV 0.2 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.3 KNN
python run_subprocess.py RegGBSCV 0.3 OLS
python run_subprocess.py RegGBSCV 0.3 Lasso
python run_subprocess.py RegGBSCV 0.3 Ridge
python run_subprocess.py RegGBSCV 0.3 ElasticNet
python run_subprocess.py RegGBSCV 0.3 DT
#python run_subprocess.py RegGBSCV 0.3 LGBM
python run_subprocess.py RegGBSCV 0.3 RF
python run_subprocess.py RegGBSCV 0.3 MLP
python run_subprocess.py RegGBSCV 0.3 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.4 KNN
python run_subprocess.py RegGBSCV 0.4 OLS
python run_subprocess.py RegGBSCV 0.4 Lasso
python run_subprocess.py RegGBSCV 0.4 Ridge
python run_subprocess.py RegGBSCV 0.4 ElasticNet
python run_subprocess.py RegGBSCV 0.4 DT
#python run_subprocess.py RegGBSCV 0.4 LGBM
python run_subprocess.py RegGBSCV 0.4 RF
python run_subprocess.py RegGBSCV 0.4 MLP
python run_subprocess.py RegGBSCV 0.4 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.5 KNN
python run_subprocess.py RegGBSCV 0.5 OLS
python run_subprocess.py RegGBSCV 0.5 Lasso
python run_subprocess.py RegGBSCV 0.5 Ridge
python run_subprocess.py RegGBSCV 0.5 ElasticNet
python run_subprocess.py RegGBSCV 0.5 DT
#python run_subprocess.py RegGBSCV 0.5 LGBM
python run_subprocess.py RegGBSCV 0.5 RF
python run_subprocess.py RegGBSCV 0.5 MLP
python run_subprocess.py RegGBSCV 0.5 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.6 KNN
python run_subprocess.py RegGBSCV 0.6 OLS
python run_subprocess.py RegGBSCV 0.6 Lasso
python run_subprocess.py RegGBSCV 0.6 Ridge
python run_subprocess.py RegGBSCV 0.6 ElasticNet
python run_subprocess.py RegGBSCV 0.6 DT
#python run_subprocess.py RegGBSCV 0.6 LGBM
python run_subprocess.py RegGBSCV 0.6 RF
python run_subprocess.py RegGBSCV 0.6 MLP
python run_subprocess.py RegGBSCV 0.6 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.7 KNN
python run_subprocess.py RegGBSCV 0.7 OLS
python run_subprocess.py RegGBSCV 0.7 Lasso
python run_subprocess.py RegGBSCV 0.7 Ridge
python run_subprocess.py RegGBSCV 0.7 ElasticNet
python run_subprocess.py RegGBSCV 0.7 DT
#python run_subprocess.py RegGBSCV 0.7 LGBM
python run_subprocess.py RegGBSCV 0.7 RF
python run_subprocess.py RegGBSCV 0.7 MLP
python run_subprocess.py RegGBSCV 0.7 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.8 KNN
python run_subprocess.py RegGBSCV 0.8 OLS
python run_subprocess.py RegGBSCV 0.8 Lasso
python run_subprocess.py RegGBSCV 0.8 Ridge
python run_subprocess.py RegGBSCV 0.8 ElasticNet
python run_subprocess.py RegGBSCV 0.8 DT
#python run_subprocess.py RegGBSCV 0.8 LGBM
python run_subprocess.py RegGBSCV 0.8 RF
python run_subprocess.py RegGBSCV 0.8 MLP
python run_subprocess.py RegGBSCV 0.8 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 0.9 KNN
python run_subprocess.py RegGBSCV 0.9 OLS
python run_subprocess.py RegGBSCV 0.9 Lasso
python run_subprocess.py RegGBSCV 0.9 Ridge
python run_subprocess.py RegGBSCV 0.9 ElasticNet
python run_subprocess.py RegGBSCV 0.9 DT
#python run_subprocess.py RegGBSCV 0.9 LGBM
python run_subprocess.py RegGBSCV 0.9 RF
python run_subprocess.py RegGBSCV 0.9 MLP
python run_subprocess.py RegGBSCV 0.9 SVM
echo RegGBSCV
python run_subprocess.py RegGBSCV 1.0 KNN
python run_subprocess.py RegGBSCV 1.0 OLS
python run_subprocess.py RegGBSCV 1.0 Lasso
python run_subprocess.py RegGBSCV 1.0 Ridge
python run_subprocess.py RegGBSCV 1.0 ElasticNet
python run_subprocess.py RegGBSCV 1.0 DT
#python run_subprocess.py RegGBSCV 1.0 LGBM
python run_subprocess.py RegGBSCV 1.0 RF
python run_subprocess.py RegGBSCV 1.0 MLP
python run_subprocess.py RegGBSCV 1.0 SVM